name: My_Portfolio_Workflow

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: auto deploy
        run: |
          echo "${{ secrets.id_rsa }}" > id_rsa
          chmod 600 id_rsa
          sudo apt update
          sudo apt install -y ansible
          ansible-playbook -i inventory.ini install_packages.yml --private-key id_rsa